export enum Rarity {
    Common = 'Common',
    Uncommon = 'Uncommon',
    Rare = 'Rare',
    AmazingRare = 'Amazing Rare',
    RareAce = 'Rare ACE',
    RareBreak = 'Rare BREAK',
    RareHolo = 'Rare Holo',
    RareHoloEX = 'Rare Holo EX',
    RareHoloGX = 'Rare Holo GX',
    RareHoloLVX = 'Rare Holo LV.X',
    RareHoloStar = 'Rare Holo Star',
    RareHoloV = 'Rare Holo V',
    RareHoloVMAX = 'Rare Holo VMAX',
    RarePrime = 'Rare Prime',
    RarePrimeStar = 'Rare Prism Star',
    RareRainbow = 'Rare Rainbow',
    RareSecret = 'Rare Secret',
    RareShining = 'Rare Shining',
    RareShiny = 'Rare Shiny',
    RareShinyGX = 'Rare Shiny GX',
    RareUltra = 'Rare Ultra',
    Legend = 'LEGEND',
    Promo = 'Promo',
}